apiVersion: openresty.huangzehong.me/v1alpha1
kind: OpenResty
metadata:
  name: openai-gw
  namespace: openai
spec:
  replicas: 1
  image: gintonic1glass/openresty:alpine-1.1.11
  http:
    include:
      - mime.types
    logFormat: |
      $remote_addr - $remote_user [$time_local] "$request" ...
    clientMaxBodySize: 16m
    gzip: true
    extra:
      - sendfile on;
      - tcp_nopush on;
    serverRefs:
      - sample-01
    upstreamRefs:
      - openai-api
      - eth-api
      - pay-api
      - weather-api
  metrics:
    enable: true
    listen: "9090"
    path: "/metrics"
  serviceMonitor:
    enable: true
    labels:
      volcengine.vmp: "true"
  reloadAgentEnv:
    - name: RELOAD_POLICY
      value: '{"window":60,"maxEvents":20}'
