apiVersion: openresty.huangzehong.me/v1alpha1
kind: Upstream
metadata:
  name: openai-api
  namespace: openai
spec:
  type: Address
  servers:
    - address: api.openai-hub.com:443
    - address: api.openai-proxy.org:443
    - address: openai.wndbac.cn:443
---
apiVersion: openresty.huangzehong.me/v1alpha1
kind: Upstream
metadata:
  name: eth-api
  namespace: openai
spec:
  type: FullURL
  servers:
    - address: https://polished-light-patina.quiknode.pro/apikey/
    - address: https://polished-light-patina.quiknode.pro/apikey/
    - address: https://skilled-serene-emerald.quiknode.pro/apikey/
---
apiVersion: openresty.huangzehong.me/v1alpha1
kind: Upstream
metadata:
  name: pay-api
  namespace: openai
spec:
  type: FullURL
  servers:
    - address: https://ghtrk-pixel.fly.dev/pay
      normalizeRequestRef:
        name: "normalize-request-standard-a"
    - address: https://ghtrk-pixel.fly.dev/pay2
      normalizeRequestRef:
        name: "normalize-request-standard-b"
---
apiVersion: openresty.huangzehong.me/v1alpha1
kind: Upstream
metadata:
  name: weather-api
  namespace: openai
spec:
  type: FullURL
  servers:
    - address: https://api.openweathermap.org/data/2.5/weather
      normalizeRequestRef:
        name: normalize-weather-query
    - address: https://api.weatherapi.com/v1/current.json
      normalizeRequestRef:
        name: normalize-weatherapi-query