apiVersion: openresty.huangzehong.me/v1alpha1
kind: Upstream
metadata:
  name: openai-api
  namespace: openai
spec:
  type: Address
  servers:
    - address: api.openai-hub.com:443
    - address: api.openai-proxy.org:443
    - address: openai.wndbac.cn:443
---
apiVersion: openresty.huangzehong.me/v1alpha1
kind: Upstream
metadata:
  name: eth-api
  namespace: openai
spec:
  type: FullURL
  servers:
    - address: https://polished-light-patina.quiknode.pro/apikey/
    - address: https://polished-light-patina.quiknode.pro/apikey/
    - address: https://skilled-serene-emerald.quiknode.pro/apikey/