apiVersion: openresty.huangzehong.me/v1alpha1
kind: Upstream
metadata:
  name: openai-api
  namespace: openai
spec:
  type: Address
  servers:
    - api.openai-hub.com:443
    - api.openai-proxy.org:443
    - openai.wndbac.cn:443
---
apiVersion: openresty.huangzehong.me/v1alpha1
kind: Upstream
metadata:
  name: eth-api
  namespace: openai
spec:
  type: FullURL
  servers:
    - https://polished-light-patina.quiknode.pro/apikey/
    - https://polished-light-patina.quiknode.pro/apikey/
    - https://skilled-serene-emerald.quiknode.pro/apikey/