---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhookserver-service
      namespace: system
      path: /validate-location
  failurePolicy: Fail
  name: validation.location.webhookserver.chillyroom.com
  rules:
  - apiGroups:
    - openresty.huangzehong.me
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - locations
  sideEffects: None
