
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{- include "openresty-operator.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - events
      - configmaps
      - secrets
    verbs: ["*"]
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs: ["*"]
  - apiGroups:
      - openresty.huangzehong.me
    resources:
      - "*"
    verbs: ["*"]
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs: [ "*" ]
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{- include "openresty-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{- include "openresty-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{- include "openresty-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
