apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openresty-operator.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "openresty-operator.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}