# permissions for end users to edit locations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openresty-operator
    app.kubernetes.io/managed-by: kustomize
  name: location-editor-role
rules:
- apiGroups:
  - web.chillyroom.com
  resources:
  - locations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - web.chillyroom.com
  resources:
  - locations/status
  verbs:
  - get
