# permissions for end users to edit openresties.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openresty-operator
    app.kubernetes.io/managed-by: kustomize
  name: openresty-editor-role
rules:
- apiGroups:
  - openresty.huangzehong.me
  resources:
  - openresties
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openresty.huangzehong.me
  resources:
  - openresties/status
  verbs:
  - get
