---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - openresty.huangzehong.me
  resources:
  - locations
  - normalizerules
  - openresties
  - ratelimitpolicies
  - serverblocks
  - upstreams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openresty.huangzehong.me
  resources:
  - locations/finalizers
  - normalizerules/finalizers
  - openresties/finalizers
  - ratelimitpolicies/finalizers
  - serverblocks/finalizers
  - upstreams/finalizers
  verbs:
  - update
- apiGroups:
  - openresty.huangzehong.me
  resources:
  - locations/status
  - normalizerules/status
  - openresties/status
  - ratelimitpolicies/status
  - serverblocks/status
  - upstreams/status
  verbs:
  - get
  - patch
  - update
