# permissions for end users to view serverblocks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openresty-operator
    app.kubernetes.io/managed-by: kustomize
  name: serverblock-viewer-role
rules:
- apiGroups:
  - openresty.huangzehong.me
  resources:
  - serverblocks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openresty.huangzehong.me
  resources:
  - serverblocks/status
  verbs:
  - get
