# permissions for end users to view upstreams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openresty-operator
    app.kubernetes.io/managed-by: kustomize
  name: upstream-viewer-role
rules:
- apiGroups:
  - openresty.huangzehong.me
  resources:
  - upstreams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openresty.huangzehong.me
  resources:
  - upstreams/status
  verbs:
  - get
