replicaCount: 1

image:
  repository: gintonic1glass/openresty-operator
  tag: v0.1.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

openresty:
  enabled: true
  name: openresty-sample
  image: gintonic1glass/openresty:with-prometheus
  replicas: 1

  http:
    accessLog: /var/log/nginx/access.log
    errorLog: /var/log/nginx/error.log
    clientMaxBodySize: 16m
    gzip: true

    serverRefs:
      - serverblock-sample
    upstreamRefs:
      - upstream-sample

upstreams:
  - name: upstream-sample
    servers:
      - backend1:8080
      - backend2:8080

serverBlocks:
  - name: serverblock-sample
    listen: "80"
    serverName:
      - example.com
    locationRefs:
      - location-sample-01
      - location-sample-02

locations:
  - name: location-sample-01
    entries:
      - path: /api-1/
        proxyPass: http://upstream-sample
        accessLog: false
  - name: location-sample-02
    entries:
      - path: /api-2/
        proxyPass: http://upstream-sample
        accessLog: false