installCRDs: true

replicaCount: 1

image:
  repository: gintonic1glass/openresty-operator
  tag: v0.2.5
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

openresty:
  name: openresty-app
  image: gintonic1glass/openresty:with-prometheus
  replicas: 1
  http:
    accessLog: /dev/stdout
    errorLog: /dev/stderr
    gzip: true
    serverRefs:
      - api-server
      - api-server02
    upstreamRefs:
      - etherscan-api
  metrics:
    enable: true
    listen: "9090"
    path: /metrics


upstreams:
  - name: etherscan-api
    servers:
      - api.etherscan.io:80
      - api.bscscan.com:80
      - api.polygonscan.com:80
      - api.ftmscan1.com:80
  - name: etherscan-api02
    servers:
      - api.etherscan.io:80
      - api.polygonscan.com:80

servers:
  - name: api-server
    listen: "80"
    locationRefs:
      - api-01
      - api-02
  - name: api-server02
    listen: "80"
    locationRefs:
      - api-01

locations:
  - name: api-01
    entries:
      - path: /api-1/
        proxyPass: http://etherscan-api
        accessLog: false
  - name: api-02
    entries:
      - path: /api-2/
        proxyPass: http://etherscan-api
        accessLog: false