installCRDs: true

replicaCount: 1

image:
  repository: gintonic1glass/openresty-operator
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

serviceMonitor:
  enabled: true
  labels: {}


openresty:
  enabled: false

# --- Example OpenRestyApp CRD ---
# Uncomment to deploy an OpenRestyApp instance
# openresty:
#   name: openresty-app                         # 必填：OpenResty 实例名称
#   image: gintonic1glass/openresty:alpine-1.1.3
#   replicas: 1
#   http:
#     accessLog: /dev/stdout
#     errorLog: /dev/stderr
#     gzip: true
#     serverRefs:
#       - api-server
#     upstreamRefs:
#       - etherscan-api
#   metrics:
#     enable: true
#     listen: "9090"
#     path: /metrics
#   serviceMonitor:
#     enabled: true
#   logVolume:
#     type: EmptyDir

# --- Example Upstream CRD ---
# upstreams:
#   - name: etherscan-api                       # 必填：用于 proxy_pass
#     servers:
#       - api.etherscan.io:443

# --- Example ServerBlock CRD ---
# servers:
#   - name: api-server
#     listen: "80"
#     locationRefs:
#       - api-01

# --- Example Location CRD ---
# locations:
#   - name: api-01
#     entries:
#       - path: /api/
#         proxyPass: https://etherscan-api/
#         enableUpstreamMetrics: true

reloadAgent:
  policies:
    window: 90
    maxEvents: 12
