{
 "title": "Openresty-Operator",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(openresty_crd_ref_status,namespace)"
    }
   },
   {
    "name": "Instance",
    "label": "Instance",
    "query": {
     "query": "label_values(openresty_crd_ref_status{kind=\"ServerBlock\", namespace=\"$namespace\"},from)"
    }
   },
   {
    "name": "servername",
    "label": "Server",
    "query": {
     "query": "label_values(openresty_crd_ref_status{kind=\"ServerBlock\", from=\"$Instance\"},to)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Operator Control Plane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OpenResty CRs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (openresty) (openresty_crd_ref_status))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ServerBlocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openresty_crd_ref_status{kind=\"ServerBlock\"})by()",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openresty_crd_ref_status{kind=\"Location\"})by()",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstreams",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openresty_crd_ref_status{kind=\"Upstream\"})by()",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream Domain × Status Code Matrix",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(\n  increase(upstream_requests_total[$__range]),\n  \"ip\", \"$1\", \"upstream\", \"([0-9.]+):[0-9]+\"\n)\n*\non (ip)\ngroup_left(server)\nlabel_replace(\n  avg(openresty_upstream_dns_resolvable{ip != \"ALL\"}) by (server, ip),\n  \"dummy\", \"1\", \"\", \"\") > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream DNS Health",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\ncount(\n  max by (server) (\n    openresty_upstream_dns_resolvable{ip=\"ALL\", prometheus=\"kube-system/prometheus-agent\"}\n  ) == 0\n)\n/\ncount(\n  max by (server) (\n    openresty_upstream_dns_resolvable{ip=\"ALL\", prometheus=\"kube-system/prometheus-agent\"}\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream Resolvability",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "openresty_upstream_dns_resolvable{prometheus=\"kube-system/prometheus-agent\", ip=\"ALL\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OpenResty Ref Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "openresty_crd_ref_status{prometheus=\"kube-system/prometheus-agent\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recent Warnings",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 10, "y": 12 },
   "targets": [
    {
     "expr": "rate(openresty_operator_event_info{type=\"Warning\"}[1m]) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Openresty", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Last Reload",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - reload_agent_reload_last_timestamp_seconds{namespace=\"${namespace}\", job=\"${Instance}-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS per Path for ${servername}.${namespace}.svc",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(sum by (ip, path) (\n  label_replace(\n    rate(upstream_requests_total{namespace=\"${namespace}\", job=\"${Instance}-metrics\", server=\"${servername}.${namespace}.svc.cluster.local\"}[1m]),\n    \"ip\", \"$1\", \"upstream\", \"^(.*):\\\\d+$\"\n  )\n)\n*\non(ip)\ngroup_left(server)\nmax by (ip, server) (\n  openresty_upstream_dns_resolvable{ip!=\"ALL\"}\n)) by(server, path)",
     "legendFormat": "{{server}} - {{path}}"
    }
   ]
  },
  {
   "title": "Average Upstream Latency (1m) for ${servername}.${namespace}.svc",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(\n  (\n    label_replace(rate(upstream_latency_seconds_sum{namespace=\"${namespace}\", job=\"${Instance}-metrics\", server=\"${servername}.${namespace}.svc.cluster.local\"}[1m]), \"ip\", \"$1\", \"upstream\", \"^(.*):\\\\d+$\")\n    /\n    label_replace(rate(upstream_latency_seconds_count{namespace=\"${namespace}\", job=\"${Instance}-metrics\", server=\"${servername}.${namespace}.svc.cluster.local\"}[1m]), \"ip\", \"$1\", \"upstream\", \"^(.*):\\\\d+$\")\n  )\n  * on(ip)\n  group_left(server, upstream)\n  openresty_upstream_dns_resolvable{ip!=\"ALL\"}\n) by (server, path)",
     "legendFormat": "({{server}}){{path}}"
    }
   ]
  },
  {
   "title": "P99 Upstream Latency for ${servername}.${namespace}.svc",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.99,\n  sum by (le, ip, path) (\n    label_replace(\n      rate(upstream_latency_seconds_bucket{namespace=\"${namespace}\", job=\"${Instance}-metrics\", server=\"${servername}.${namespace}.svc.cluster.local\"}[5m]),\n      \"ip\", \"$1\", \"upstream\", \"^(.*):\\\\d+$\"\n    )\n  )\n)\n* on(ip)\ngroup_left(server)\navg(openresty_upstream_dns_resolvable{ip!=\"ALL\"})by(ip, server)) by(server, path)",
     "legendFormat": "{{server}} - {{path}}"
    }
   ]
  }
 ]
}