apiVersion: v1
entries:
  openresty-operator:
  - apiVersion: v2
    appVersion: v0.2.9
    created: "2025-04-23T08:19:32.086169+08:00"
    description: Kubernetes Operator for managing OpenResty with custom CRDs (OpenResty,
      Server, Location, Upstream, RateLimitPolicy)
    digest: 4e26cee485c8b0d185339fe00ab06f6f7c9971a107d51e8c5947b1276fed1606
    home: https://github.com/huangzehong/openresty-operator
    keywords:
    - openresty
    - operator
    - kubernetes
    - crd
    - nginx
    - metrics
    maintainers:
    - email: zehong.hongframe.huang@gmail.com
      name: zehong.huang
    name: openresty-operator
    sources:
    - https://github.com/huangzehong/openresty-operator
    type: application
    urls:
    - https://zehonghuang.github.io/openresty-operator/charts/openresty-operator-0.2.0.tgz
    version: 0.2.0
generated: "2025-04-23T08:19:32.085069+08:00"
