apiVersion: openresty.huangzehong.me/v1alpha1
kind: NormalizeRule
metadata:
  labels:
    app.kubernetes.io/name: openresty-operator
    app.kubernetes.io/managed-by: kustomize
  name: normalizerule-sample
spec:
  # TODO(user): Add fields here
