apiVersion: openresty.huangzehong.me/v1alpha1
kind: RateLimitPolicy
metadata:
  name: ratelimitpolicy-sample
spec:
  zoneName: login_zone
  rate: 10r/s
  burst: 20
  nodelay: true
  zoneSize: 10m  # optional, default 10m
