apiVersion: openresty.huangzehong.me/v1alpha1
kind: Location
metadata:
  name: location-sample-01
spec:
  entries:
    - path: /api-1/
      proxyPass: https://etherscan-api/
      enableUpstreamMetrics: true
      accessLog: false
      headersFromSecret:
        - headerName: apiKey
          secretName: apikey
          secretKey: apikey
      extra:
        - "proxy_redirect off;"
        - "proxy_ssl_server_name on;"
    - path: /api-2/
      proxyPass: https://etherscan-api/
      enableUpstreamMetrics: true
      accessLog: false
      extra:
        - "proxy_redirect off;"
        - "proxy_ssl_server_name on;"
---
apiVersion: openresty.huangzehong.me/v1alpha1
kind: Location
metadata:
  name: location-sample-02
spec:
  entries:
    - path: /api-3/
      proxyPass: https://etherscan-api/
      enableUpstreamMetrics: true
      accessLog: false
      extra:
        - "proxy_redirect off;"
        - "proxy_ssl_server_name on;"
    - path: /api-4/
      proxyPass: https://etherscan-api/
      enableUpstreamMetrics: true
      accessLog: false
      extra:
        - "proxy_redirect off;"
        - "proxy_ssl_server_name on;"
    - path: /api-0545210-c32e3/
      proxyPass: https://etherscan-api/
      enableUpstreamMetrics: true
      accessLog: false
      extra:
        - "proxy_redirect off;"
        - "proxy_ssl_server_name on;"
    - path: /api-7/
      proxyPass: https://etherscan-api/
      enableUpstreamMetrics: true
      accessLog: false
      extra:
        - "proxy_redirect off;"
        - "proxy_ssl_server_name on;"
---
apiVersion: openresty.huangzehong.me/v1alpha1
kind: Location
metadata:
  name: eth-sample
spec:
  entries:
    - path: /eth-api/
      proxyPass: https://eth-api/
      proxyPassIsFullURL: true
      enableUpstreamMetrics: true
      accessLog: false
      extra:
        - "proxy_redirect off;"
        - "proxy_ssl_server_name on;"
---