apiVersion: openresty.huangzehong.me/v1alpha1
kind: Upstream
metadata:
  labels:
    app.kubernetes.io/name: openresty-operator
    app.kubernetes.io/managed-by: kustomize
  name: upstream-sample
spec:
  servers:
    - example.com:80
    - www.baidu.com:443
    - invalid.domain.local:8080
