apiVersion: web.chillyroom.com/v1alpha1
kind: Location
metadata:
  labels:
    app.kubernetes.io/name: openresty-operator
    app.kubernetes.io/managed-by: kustomize
  name: location-sample-01
spec:
  entries:
    - path: /api-1/
      proxyPass: http://upstream-sample
      enableUpstreamMetrics: true
      headers:
        - key: Host
          value: $host
        - key: X-Real-IP
          value: $remote_addr
        - key: X-Forwarded-For
          value: $proxy_add_x_forwarded_for
        - key: X-Forwarded-Proto
          value: $scheme
        - key: X-Content-Type-Options
          value: nosniff
        - key: Access-Control-Allow-Origin
          value: "*"
      timeout:
        connect: 5s
        send: 10s
        read: 10s
      accessLog: false
      gzip:
        enable: true
        types:
          - text/plain
          - application/json
      lua:
        access: |
          if not ngx.var.arg_token then
              return ngx.exit(401)
          end
---
apiVersion: web.chillyroom.com/v1alpha1
kind: Location
metadata:
  labels:
    app.kubernetes.io/name: openresty-operator
    app.kubernetes.io/managed-by: kustomize
  name: location-sample-02
spec:
  entries:
    - path: /api-2/
      proxyPass: http://upstream-sample
      enableUpstreamMetrics: true
      headers:
        - key: Host
          value: $host
        - key: X-Real-IP
          value: $remote_addr
        - key: X-Forwarded-For
          value: $proxy_add_x_forwarded_for
        - key: X-Forwarded-Proto
          value: $scheme
        - key: X-Content-Type-Options
          value: nosniff
        - key: Access-Control-Allow-Origin
          value: "*"
      timeout:
        connect: 5s
        send: 10s
        read: 10s
      accessLog: false
      gzip:
        enable: true
        types:
          - text/plain
          - application/json
      lua:
        access: |
          if not ngx.var.arg_token then
              return ngx.exit(401)
          end
