apiVersion: openresty.huangzehong.me/v1alpha1
kind: Upstream
metadata:
  labels:
    app.kubernetes.io/name: openresty-operator
    app.kubernetes.io/managed-by: kustomize
  name: etherscan-api
spec:
  servers:
    - api.etherscan.io:443
    - api.bscscan.com:443
    - api.polygonscan.com:443
    - api.ftmscan1.com:443
