apiVersion: openresty.huangzehong.me/v1alpha1
kind: Upstream
metadata:
  name: etherscan-api
spec:
  servers:
    - api.etherscan.io:443
    - api.bscscan.com:443
    - api.polygonscan.com:443
    - api.ftmscan1.com:443
