apiVersion: web.chillyroom.com/v1alpha1
kind: Upstream
metadata:
  labels:
    app.kubernetes.io/name: openresty-operator
    app.kubernetes.io/managed-by: kustomize
  name: upstream-sample
spec:
  # TODO(user): Add fields here
