# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/openresty.huangzehong.me_openresties.yaml
- bases/openresty.huangzehong.me_upstreams.yaml
- bases/openresty.huangzehong.me_locations.yaml
- bases/openresty.huangzehong.me_serverblocks.yaml
- bases/openresty.huangzehong.me_ratelimitpolicies.yaml
- bases/openresty.huangzehong.me_normalizerules.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhookserver, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhookserver for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_openresties.yaml
#- path: patches/cainjection_in_upstreams.yaml
#- path: patches/cainjection_in_locations.yaml
#- path: patches/cainjection_in_serverblocks.yaml
#- path: patches/cainjection_in_ratelimitpolicies.yaml
#- path: patches/cainjection_in_normalizerules.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# [WEBHOOK] To enable webhookserver, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.

#configurations:
#- kustomizeconfig.yaml
