name: Release Helm Chart

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (source)
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Configure Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Package Helm chart
        run: |
          mkdir -p chart-dist
          helm package charts/openresty-operator --destination chart-dist

      - name: Checkout gh-pages branch (for previous index)
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy previous index.yaml if exists
        run: |
          if [ -f gh-pages/index.yaml ]; then
            cp gh-pages/index.yaml chart-dist/index.yaml
          else
            echo "No previous index.yaml found, creating a new one"
          fi

      - name: Generate or merge Helm index.yaml
        run: |
          helm repo index chart-dist \
            --url https://huangzehong.me/openresty-operator \
            --merge chart-dist/index.yaml || true

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: chart-dist
