name: Release Operator & Helm Chart

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

env:
  IMAGE_REPO: gintonic1glass/openresty-operator

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_REPO:${{ steps.vars.outputs.VERSION }} .
          docker push $IMAGE_REPO:${{ steps.vars.outputs.VERSION }}

      - name: Update Helm chart version and image tag
        run: |
          VERSION=${{ steps.vars.outputs.VERSION }}

          # 更新 values.yaml 中的镜像 tag
          sed -i "s/^ *tag: .*/  tag: \"${VERSION}\"/" charts/openresty-operator/values.yaml

          # 更新 Chart.yaml 中的 version 和 appVersion
          sed -i "s/^version: .*/version: ${VERSION}/" charts/openresty-operator/Chart.yaml
          sed -i "s/^appVersion: .*/appVersion: \"${VERSION}\"/" charts/openresty-operator/Chart.yaml

          # 提交这些修改
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add charts/openresty-operator/values.yaml charts/openresty-operator/Chart.yaml
          git commit -m "chore: update Helm chart version to v${VERSION}"
          git push origin HEAD:main

      - name: Package Helm chart
        run: |
          mkdir -p chart-dist
          helm package charts/openresty-operator --destination chart-dist

      - name: Checkout gh-pages for index
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy existing index.yaml if exists
        run: |
          cp gh-pages/index.yaml chart-dist/index.yaml || echo "No previous index"

      - name: Merge and regenerate Helm index.yaml
        run: |
          helm repo index chart-dist \
            --url https://huangzehong.me/openresty-operator \
            --merge chart-dist/index.yaml || true

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: chart-dist
          keep_files: true
